[package]
name = "A8mini-gimbal-camera-control-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
bytes = "1"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
